#pragma once

#include <GL/glut.h>

namespace Objects
{

		/**
		 * A texture defines the information about the texture, as well as helper methods to bind and unbind the texture.
		 * @author Mathew Causby
		 * @version 0.1
		 */
	class Texture
	{
	public:
		Texture();
		Texture(const Texture & other);
		~Texture();

			/**
			 * Binds the texture so that it can be drawn over a model.
			 */
		void Bind();
			/**
			 * Unbinds the texture.
			 */
		void Unbind();
			/**
			 * Destroys the texture and free's the memory.
			 */
		void Destroy();
			/**
			 * Sets the texture ID generated by OpenGL.
			 * @param[in] texId The ID of the texture.
			 */
		void SetTextureID(int texId);
			/**
			 * Gets the texture ID.
			 * @return The ID of the texture.
			 */
		int GetTextureID();

	private:
		GLuint m_textureId;
	};

}